// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feeds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addfeed = `-- name: Addfeed :one
INSERT INTO feeds (name, url, user_id)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, name, url, user_id
`

type AddfeedParams struct {
	Name   string
	Url    string
	UserID uuid.UUID
}

func (q *Queries) Addfeed(ctx context.Context, arg AddfeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, addfeed, arg.Name, arg.Url, arg.UserID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
